name: RTI Monitor

on:
  schedule:
    - cron: "0 23 * * *"   # 每天 UTC 23:00 執行（台灣時間早上 7 點）
  workflow_dispatch:       # 允許手動觸發

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run monitor script
        run: |
          mkdir -p out
          python monitor_stdlib.py config-stdlib.json --date $(date -u +%Y-%m-%d)
          cp out/*.json latest.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .
