name: RTI Monitor

on:
  schedule:
    - cron: "0 23 * * *"  # 每天 UTC 23:00
  workflow_dispatch:       # 手動觸發也可

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run monitor
        run: |
          python monitor_stdlib.py config-stdlib.json --date $(date -u +%Y-%m-%d)

      - name: Copy output to web
        run: |
          mkdir -p public
          cp out/*.json public/latest.json

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
