name: RTI Monitor

on:
  schedule:
    - cron: "0 23 * * *"   # 每天 UTC 23:00（台灣早上 07:00）
  workflow_dispatch:        # 允許手動觸發
  push:
    branches: [ main ]      # push 到 main 也會跑
    paths:
      - "monitor_stdlib.py"
      - "config-stdlib.json"
      - "index.html"
      - ".github/workflows/monitor.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run monitor
        run: |
          mkdir -p out
          # 以「今天的 UTC 日期」跑；若想固定跑「台北今天」，可改用 TZ=Asia/Taipei
          python monitor_stdlib.py config-stdlib.json --date $(date -u +%Y-%m-%d)
          ls -lh out

      - name: Prepare website folder
        run: |
          mkdir -p public
          # 固定命名為 latest.json，供前端讀取
          cp -v out/*.json public/latest.json || echo "no json found"
          # 可選：同步一份 CSV 方便下載
          if ls out/*.csv 1> /dev/null 2>&1; then cp -v out/*.csv public/latest.csv; fi
          # 發佈 index.html（確保和 latest.json 同資料夾）
          cp -v index.html public/index.html
          # 禁用 Jekyll
          touch public/.nojekyll
          ls -lh public

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
