name: RTI Monitor

on:
  schedule:
    - cron: "0 23 * * *"   # 每天 UTC+0 23:00 跑一次
  workflow_dispatch:       # 手動觸發

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Run monitor script
      run: |
        python monitor_stdlib.py config-stdlib.json --date $(date -u +%Y-%m-%d)

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
        publish_branch: gh-pages
