name: RTI Monitor

on:
  schedule:
    - cron: "0 23 * * *"  # 每天 UTC 23:00
  workflow_dispatch:      # 手動觸發也可以

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run monitor
        run: |
          python monitor_stdlib.py config-stdlib.json --date $(date -u +"%Y-%m-%d")
      
      - name: Deploy to gh-pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # 建一個乾淨的資料夾
          rm -rf public
          mkdir -p public

          # 複製輸出的最新 JSON/CSV
          cp out/*.json public/
          cp out/*.csv public/

          # 把最後一份 JSON 複製成 latest.json
          cp $(ls -t out/*.json | head -n 1) public/latest.json

          # 複製 index.html
          cp index.html public/

          cd public
          git init
          git checkout -b gh-pages
          git add .
          git commit -m "Deploy latest report"
          git push --force "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" gh-pages
